spring:
  application:
    name: dsm-hackathon-21

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}

    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      auto-index-creation: true

mail:
  sender:
    host: ${MAIL_SENDER_HOST}
    email: ${MAIL_SENDER_EMAIL}
    password: ${MAIL_SENDER_PASSWORD}
    auth: ${MAIL_SENDER_AUTH}
    starttls-required: ${MAIL_SENDER_STARTTLS_REQUIRED}
    starttls-enable: ${MAIL_SENDER_STARTTLS_ENABLE}
    socket-factory-class: ${MAIL_SENDER_SOCKET_CLASS}
    socket-factory-fallback: ${MAIL_SENDER_SOCKET_FALLBACK}
    port: ${MAIL_SENDER_PORT}

jwt:
  secret: ddd

translate:
  api:
    url: http://localhost:5001
