spring:
  application:
    name: dsm-hackathon-21

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
      auto-index-creation: true

translate:
  api:
    url: http://localhost:5001
